# Generated by Django 3.2.9 on 2021-12-03 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_auto_20211202_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 10, 25, 1, 910803)),
        ),
    ]
