# Generated by Django 3.2.6 on 2021-12-03 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_auto_20211203_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 14, 57, 33, 791803)),
        ),
    ]
