# Generated by Django 3.2.6 on 2021-12-03 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_sale_book_store_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_info_tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_persions_name', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_persions_email', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_persions_subjects', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_persions_massages', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Info Tabel',
            },
        ),
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 19, 9, 31, 871437)),
        ),
    ]
