# Generated by Django 3.2.6 on 2021-12-03 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_auto_20211203_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 19, 10, 4, 862833)),
        ),
    ]
