# Generated by Django 3.2.6 on 2021-12-03 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_1', '0014_auto_20211203_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 21, 37, 46, 452528)),
        ),
        migrations.CreateModel(
            name='wish_list_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wish_time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 21, 37, 46, 455520))),
                ('Wish_persions', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Wish_product', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.sale_book')),
            ],
            options={
                'verbose_name_plural': 'Wish List Table',
            },
        ),
    ]
