# Generated by Django 3.2.6 on 2021-12-03 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0017_auto_20211203_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_book',
            name='store_post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 21, 43, 16, 720040)),
        ),
        migrations.AlterField(
            model_name='wish_list_table',
            name='Wish_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 3, 21, 43, 16, 722023)),
        ),
    ]
